// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3sMdFu-bgCawo90n1DcVEsByGGlEl9Js',
    appId: '1:103739738633:web:0737ffd9b456e5bfaa86d8',
    messagingSenderId: '103739738633',
    projectId: 'flutter-video-audio-chat-app',
    authDomain: 'flutter-video-audio-chat-app.firebaseapp.com',
    storageBucket: 'flutter-video-audio-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJfd66ypb8-Zye3AJMnBFEPpHRhNqlpI',
    appId: '1:103739738633:android:1edda3416dc0b6b9aa86d8',
    messagingSenderId: '103739738633',
    projectId: 'flutter-video-audio-chat-app',
    storageBucket: 'flutter-video-audio-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjdEpMxRfY2Ig9w4X0PU2ZVW1MZkK-_i4',
    appId: '1:103739738633:ios:534fa110d7d9dacbaa86d8',
    messagingSenderId: '103739738633',
    projectId: 'flutter-video-audio-chat-app',
    storageBucket: 'flutter-video-audio-chat-app.appspot.com',
    androidClientId: '103739738633-3i91v839g57pncdkmjaqrgr45t78lrbp.apps.googleusercontent.com',
    iosClientId: '103739738633-5nkh70s198j575lej3sck0aucbfoipt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjdEpMxRfY2Ig9w4X0PU2ZVW1MZkK-_i4',
    appId: '1:103739738633:ios:534fa110d7d9dacbaa86d8',
    messagingSenderId: '103739738633',
    projectId: 'flutter-video-audio-chat-app',
    storageBucket: 'flutter-video-audio-chat-app.appspot.com',
    androidClientId: '103739738633-3i91v839g57pncdkmjaqrgr45t78lrbp.apps.googleusercontent.com',
    iosClientId: '103739738633-5nkh70s198j575lej3sck0aucbfoipt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoChatApp',
  );
}
